version: "3.8"

services: 
    redis:
        container_name: redis
        image: redis:6
        ports:
            - 6379:6379
        volumes:
            - redis_data:/bitnami/redis/data

volumes:
    redis_data:
        driver: local

networks:
    kafka-net:
        driver: bridge